#if defined EUTILS_INC
	#endscript
else
	#if defined EUTILS_INC_COLORS
		#endscript
	#endif
#endif

#define EUTILS_INC_COLORS

#if !defined COLOR_GRAY
	#define COLOR_GRAY 0xAFAFAFAA
#endif
#if !defined COLOR_GREEN
	#define COLOR_GREEN 0x00FF00FF
#endif
#if !defined COLOR_RED
	#define COLOR_RED 0xFF0000FF
#endif
#if !defined COLOR_YELLOW
	#define COLOR_YELLOW 0xFFFF00FF
#endif
#if !defined COLOR_WHITE
	#define COLOR_WHITE 0xFFFFFFAA
#endif
#if !defined COLOR_BLUE
	#define COLOR_BLUE 0x0000FFFF
#endif
#if !defined COLOR_LIGHTBLUE
	#define COLOR_LIGHTBLUE 0x33CCFFAA
#endif
#if !defined COLOR_ORANGE
	#define COLOR_ORANGE 0xFF9900FF
#endif
#if !defined COLOR_LIME
	#define COLOR_LIME 0x10F441AA
#endif
#if !defined COLOR_MAGENTA
	#define COLOR_MAGENTA 0xFF00FFFF
#endif
#if !defined COLOR_NAVY
	#define COLOR_NAVY 0x000080AA
#endif
#if !defined COLOR_AQUA
	#define COLOR_AQUA 0xF0F8FFAA
#endif
#if !defined COLOR_CRIMSON
	#define COLOR_CRIMSON 0xDC143CAA
#endif
#if !defined COLOR_FLBLUE
	#define COLOR_FLBLUE 0x6495EDAA
#endif
#if !defined COLOR_BISQUE
	#define COLOR_BISQUE 0xFFE4C4AA
#endif
#if !defined COLOR_BLACK
	#define COLOR_BLACK 0x000000FF
#endif
#if !defined COLOR_CHARTREUSE
	#define COLOR_CHARTREUSE 0x7FFF00AA
#endif
#if !defined COLOR_BROWN
	#define COLOR_BROWN 0XA52A2AAA
#endif
#if !defined COLOR_CORAL
	#define COLOR_CORAL 0xFF7F50AA
#endif
#if !defined COLOR_GOLD
	#define COLOR_GOLD 0xB8860BAA
#endif
#if !defined COLOR_GREENYELLOW
	#define COLOR_GREENYELLOW 0xADFF2FAA
#endif
#if !defined COLOR_INDIGO
	#define COLOR_INDIGO 0x4B00B0AA
#endif
#if !defined COLOR_IVODY
	#define COLOR_IVORY 0xFFFF82AA
#endif
#if !defined COLOR_LAWNGREEN
	#define COLOR_LAWNGREEN 0x7CFC00AA
#endif
#if !defined COLOR_SEAGREEN
	#define COLOR_SEAGREEN 0x20B2AAAA
#endif
#if !defined COLOR_LIMEGREEN
	#define COLOR_LIMEGREEN 0x32CD32AA
#endif
#if !defined COLOR_MIDNIGHTBLUE
	#define COLOR_MIDNIGHTBLUE 0X191970AA
#endif
#if !defined COLOR_MAROON
	#define COLOR_MAROON 0x800000AA
#endif
#if !defined COLOR_OLIVE
	#define COLOR_OLIVE 0x808000AA
#endif
#if !defined COLOR_ORANGERED
	#define COLOR_ORANGERED 0xFF4500AA
#endif
#if !defined COLOR_PINK
	#define COLOR_PINK 0xFFC0CBAA
#endif
#if !defined COLOR_SPRINGGREEN
	#define COLOR_SPRINGGREEN 0x00FF7FAA
#endif
#if !defined COLOR_TOMATO
	#define COLOR_TOMATO 0xFF6347AA
#endif
#if !defined COLOR_YELLOWGREEN
	#define COLOR_YELLOWGREEN 0x9ACD32AA
#endif
#if !defined COLOR_MEDIUMAQUA
	#define COLOR_MEDIUMAQUA 0x83BFBFAA
#endif
#if !defined COLOR_MEDIUMMAGENTA
	#define COLOR_MEDIUMMAGENTA 0x8B008BAA
#endif
#if !defined COLOR_THCGREEN
	#define COLOR_THCGREEN 0x00FF88AA
#endif

#if !defined BEMBED_ASAY
	#define BEMBED_ASAY "{FF0000}"
#endif
#if !defined BEMBED_OSAY
	#define BEMBED_OSAY "{007700}"
#endif
#if !defined BEMBED_HSAY
	#define BEMBED_HSAY "{1684CA}"
#endif
#if !defined BEMBED_LRED
	#define BEMBED_LRED "{FF4747}"
#endif
#if !defined BEMBED_LGREEN
	#define BEMBED_LGREEN "{00FF99}"
#endif
#if !defined BEMBED_LBLUE
	#define BEMBED_LBLUE "{99FFFF}"
#endif
#if !defined BEMBED_PURPLE
	#define BEMBED_PURPLE "{CC00DD}"
#endif
#if !defined BEMBED_PEACH
	#define BEMBED_PEACH "{FFCC66}"
#endif
#if !defined BEMBED_SILVER
	#define BEMBED_SILVER "{DDDDDD}"
#endif
#if !defined BEMBED_WANTEDBLUE
	#define BEMBED_WANTEDBLUE "{0055CC}"
#endif
#if !defined BEMBED_VIOLET
	#define BEMBED_DARK_VIOLET "{9400D3}"
#endif
#if !defined BEMBED_SUPPORT
	#define BEMBED_SUPPORT "{00E5EE}"
#endif
#if !defined BEMBED_ADMIN
	#define BEMBED_ADMIN "{00CCFF}"
#endif
#if !defined BEMBED_PLAYER
	#define BEMBED_PLAYER "{FFFF33}"
#endif
#if !defined BEMBED_VIP1
	#define BEMBED_VIP1 "{C0C0C0}"
#endif
#if !defined BEMBED_VIP2
	#define BECKZY_VIP2 "{DAA520}"
#endif

#if !defined BECKZY_ASAY
	#define BECKZY_ASAY 0xFF0000FF
#endif
#if !defined BECKZY_OSAY
	#define BECKZY_OSAY 0x007700FF
#endif
#if !defined BECKZY_HSAY
	#define BECKZY_HSAY 0x1684CAFF
#endif
#if !defined BECKZY_LRED
	#define BECKZY_LRED 0xFF4747FF
#endif
#if !defined BECKZY_LGREEN
	#define BECKZY_LGREEN 0x00FF9900
#endif
#if !defined BECKZY_LBLUE
	#define BECKZY_LBLUE 0x99FFFFFF
#endif
#if !defined BECKZY_PURPLE
	#define BECKZY_PURPLE 0xCC00DDFF
#endif
#if !defined BECKZY_PEACH
	#define BECKZY_PEACH 0xFFCC66FF
#endif
#if !defined BECKZY_SILVER
	#define BECKZY_SILVER 0xDDDDDDFF
#endif
#if !defined BECKZY_WANTEDBLUE
	#define BECKZY_WANTEDBLUE 0x0055CCFF
#endif
#if !defined BECKZY_VIOLET
	#define BECKZY_DARK_VIOLET 0x9400D3FF
#endif
#if !defined BECKZY_SUPPORT
	#define BECKZY_SUPPORT 0x00E5EEFF
#endif
#if !defined BECKZY_ADMIN
	#define BECKZY_ADMIN 0x00CCFF66
#endif
#if !defined BECKZY_PLAYER
	#define BECKZY_PLAYER 0xFFFF33FF
#endif
#if !defined BECKZY_VIP1
	#define BECKZY_VIP1 0xC0C0C0FF
#endif
#if !defined BECKZY_VIP2
	#define BECKZY_VIP2 0xDAA520FF
#endif

#if !defined EMBED_GRAY
	#define EMBED_GRAY "{AFAFAF}"
#endif
#if !defined EMBED_GREEN
	#define EMBED_GREEN "{00FF00}"
#endif
#if !defined EMBED_RED
	#define EMBED_RED "{FF0000}"
#endif
#if !defined EMBED_YELLOW
	#define EMBED_YELLOW "{FFFF00}"
#endif
#if !defined EMBED_WHITE
	#define EMBED_WHITE "{FFFFFF}"
#endif
#if !defined EMBED_BLUE
	#define EMBED_BLUE "{0000FF}"
#endif
#if !defined EMBED_LIGHTBLUE
	#define EMBED_LIGHTBLUE "{33CCFF}"
#endif
#if !defined EMBED_ORANGE
	#define EMBED_ORANGE "{FF9900}"
#endif
#if !defined EMBED_LIME
	#define EMBED_LIME "{10F441}"
#endif
#if !defined EMBED_MAGENTA
	#define EMBED_MAGENTA "{FF00FF}"
#endif
#if !defined EMBED_NAVY
	#define EMBED_NAVY "{000080}"
#endif
#if !defined EMBED_AQUA
	#define EMBED_AQUA "{F0F8FF}"
#endif
#if !defined EMBED_CRIMSON
	#define EMBED_CRIMSON "{DC143C}"
#endif
#if !defined EMBED_FLBLUE
	#define EMBED_FLBLUE "{6495ED}"
#endif
#if !defined EMBED_BISQUE
	#define EMBED_BISQUE "{FFE4C4}"
#endif
#if !defined EMBED_BLACK
	#define EMBED_BLACK "{000000}"
#endif
#if !defined EMBED_CHARTREUSE
	#define EMBED_CHARTREUSE "{7FFF00}"
#endif
#if !defined EMBED_BROWN
	#define EMBED_BROWN "{A52A2A}"
#endif
#if !defined EMBED_CORAL
	#define EMBED_CORAL "{FF7F50}"
#endif
#if !defined EMBED_GOLD
	#define EMBED_GOLD "{B8860B}"
#endif
#if !defined EMBED_GREENYELLOW
	#define EMBED_GREENYELLOW "{ADFF2F}"
#endif
#if !defined EMBED_INDIGO
	#define EMBED_INDIGO "{4B00B0}"
#endif
#if !defined EMBED_IVORY
	#define EMBED_IVORY "{FFFF82}"
#endif
#if !defined EMBED_LAWNGREEN
	#define EMBED_LAWNGREEN "{7CFC00}"
#endif
#if !defined EMBED_SEAGREEN
	#define EMBED_SEAGREEN "{20B2AA}"
#endif
#if !defined EMBED_LIMEGREEN
	#define EMBED_LIMEGREEN "{32CD32}"
#endif
#if !defined EMBED_MIDNIGHTBLUE
	#define EMBED_MIDNIGHTBLUE "{191970}"
#endif
#if !defined EMBED_MAROON
	#define EMBED_MAROON "{800000}"
#endif
#if !defined EMBED_OLIVE
	#define EMBED_OLIVE "{808000}"
#endif
#if !defined EMBED_ORANGERED
	#define EMBED_ORANGERED "{FF4500}"
#endif
#if !defined EMBED_PINK
	#define EMBED_PINK "{FFC0CB}"
#endif
#if !defined EMBED_SPRINGGREEN
	#define EMBED_SPRINGGREEN "{00FF7F}"
#endif
#if !defined EMBED_TOMATO
	#define EMBED_TOMATO "{FF6347}"
#endif
#if !defined EMBED_YELLOWGREEN
	#define EMBED_YELLOWGREEN "{9ACD32}"
#endif
#if !defined EMBED_MEDIUMAQUA
	#define EMBED_MEDIUMAQUA "{83BFBF}"
#endif
#if !defined EMBED_MESIUMMAGENTA
	#define EMBED_MEDIUMMAGENTA "{8B008B}"
#endif
#if !defined EMBED_THCGREEN
	#define EMBED_THCGREEN "{00FF88}"
#endif

